---
title: "Survey_Mock_Analysis"
author: "Erin Johnston"
date: "11/24/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = F,
                      message = F)

```

Section 1) Angler Involvement

QUESTION 1: one answer, *nominal/ordinal* (?)

QUESTION 2: one answer, *ordinal*

QUESTION 3: one answer, *interval*

QUESTION 4: one answer, *nominal*

QUESTION 5: multiple answers, *nominal*

QUESTION 6: multiple answers, *nominal*

QUESTION 7: multiple answers, *nominal*

QUESTION 8: one answer, yes/no (?) *nominal*


Section 2) Marine Protected Areas

done QUESTION 9: one answer, *ordinal*... except 'no opinion'

QUESTION 10: multiple answers, *nominal/ordinal* (?)

done QUESTION 11: one answer, *ordinal*... except 'no opinion'

QUESTION 12: multiple answers, *nominal/ordinal* (?)

QUESTION 13: multiple answers, *nominal*

QUESTION 14: multiple answers, *nominal*

*done* QUESTION 15: one answer, yes/no (?), *nominal*

*done* QUESTIONS 16 a-c: one answer each, *nominal*

*done* QUESTION 17: one answer, *nominal*

*done* QUESTION 18: one answer, *interval*


Section 3) Natural Resource Conservation

*done* QUESTION 19: one answer, *nominal*

*done* QUESTION 20: one answer, yes/no (?), *nominal*

QUESTION 21: one answer, *ordinal*

QUESTION 22: multiple answers, *nominal*

*done* QUESTION 23: one answer, *ordinal*

QUESTION 24: rank order impacts, *ordinal*

QUESTION 25: rank order agreement, *ordinal/interval* (likert-scale)

QUESTION 26: one answer, *ordinal*


Section 4) Basic Demographics

*done (map)* QUESTION 27: one answer, *nominal*

*done* QUESTION 28: one answer, *nominal*

*done* QUESTION 29: one answer, *interval*

*done* QUESTION 30: one answer, *nominal/ordinal*

*done* QUESTION 31: one answer, *interval*

QUESTION 32: multiple answers, *nominal*

QUESTION 33: one answer, yes/no (?) *nominal*

QUESTION 34: one answer, yes/no (?) *nominal*

QUESTION 35: comments, *nominal*


## Directions

What are some 'essential context' to help us understand some of the questions being asked?

What are the impacts of effort (like the angler workshops) on the angler opinions of MPAs?